version: "3.2"

services:
#  nginx:
#    image: library/nginx:latest
#    ports:
#      - "${NGINX_DEFAULT_PORT}:80"
#      - "${NGINX_PORT}:443"
#    volumes:
#      - ./hosts:/etc/nginx/conf.d
#      - ./www:/var/www
#      - ./logs:/var/log/nginx
#    links:
#      - php
  php:
    build: ./images/php
    links:
      - db
    volumes:
      - ./www:/var/www
  db:
    image: library/mysql:8
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql/
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} --password=${MYSQL_PASS}
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    image: library/phpmyadmin:latest
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - PMA_HOST=db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PHP_ADMIN_PORT}:80"

volumes:
  mysql-data:
